Update setup.py and MANIFEST.in to include environment files and add …
Farama-Foundation/MAgent2 pull request #38
Opened 2024-07-16 21:23 UTC by atstarke

Provides fix for issue #14 
-Fixed pip install issues. Updates to setup.py and MANIFEST.in 
-Now, pip installing should ensure that the environments are included in the library's installation.

2024-07-31 00:19 UTC, mwydmuch requested changes
+ pre-commit checks need to be fixed.

2024-07-31 00:19 UTC, mwydmuch commented on tests/test_magent2.py
> +    assert adversarial_pursuit_v4 is not None, "adversarial_pursuit_v4 should be importable"
I think it is not a good test for imports. If `from magent2.environments import adversarial_pursuit_v4` fails in line 3, the ImportError will be raised, and no test will be run. If we want to test import, we need to put it inside the `try except` block, e.g.:

```
try:
    from magent2.environments import adversarial_pursuit_v4
except ImportError as e:
    assert False, "adversarial_pursuit_v4 should be importable"
```

2024-07-31 00:19 UTC, mwydmuch commented on tests/test_magent2.py
> +    assert adversarial_pursuit_v4 is not None, "adversarial_pursuit_v4 should be importable"
Instead of doing it one by one, the list of environment modules can be created at the beginning as a list of strings, and then they can be imported in the loop by using __import__. This will reduce redundancy. But this is NIT.

2024-07-31 00:19 UTC, mwydmuch commented on tests/test_magent2.py
> +    assert magent2.__version__ is not None, "Version should not be None"
This is not a good way to test if an object has an attribute. `hasattr(magent2, '__version__')` should be used instead in the assert.

2024-08-10 09:18 UTC, mwydmuch reviewed
I have more comments regarding this PR, it is generally ok, but some stuff seems to be unnecessary addition.

2024-08-10 09:18 UTC, mwydmuch commented on tests/test_magent2.py
> +for env in envs:
This loop is redundant to `test_import_environment`, I'm not sure what is the purpose of testing it in two places.
I would move the content of this loop into `test_import_environment`.

2024-08-10 09:18 UTC, mwydmuch commented on setup.py
> +        'pettingzoo',
Is pettingzoo really an install requirement (is it needed for the package to be installed)? I don't know certainly, but it is rather unlikely. pettingzoo is already listed in pyproject.toml file as a dependency.
Also, if it's indeed needed as install requirement, then it would be good to move this to pyproject.toml and add minimal version.

2024-08-10 09:18 UTC, mwydmuch commented on setup.py
> +        'pettingzoo',
To be clear, this addition does not cause any issues but is probably unnecessary.

2024-08-10 09:19 UTC, mwydmuch commented
I don't have the right to approve workflows for this repo; should I ask someone? Or will you do it @atstarke?

2024-08-11 14:38 UTC, atstarke commented on setup.py
> +        'pettingzoo',
Agree, I understand it to be a dependency rather than a requirement as defined here. I will remove these lines.

2024-08-11 14:38 UTC, atstarke commented on tests/test_magent2.py
> +for env in envs:
Acknowledged. Not sure why I did that, I'll fix it.

2024-08-16 20:48 UTC, mwydmuch approved these changes
All looks good!

2024-08-16 21:03 UTC, merged